import { AppSettings } from '../types';

export const DEFAULT_SETTINGS: AppSettings = {
  autoCapture: true,
  maxItems: 100,
  doubleClickPaste: true,
  darkMode: false,
  globalShortcut: 'Alt+V',
  immersiveShortcut: 'Ctrl+Shift+Z',
  autoClearDays: 30,
  hideOnAction: true,
  hideOnDrag: true,
  hideAfterDrag: true,
  showDragDownloadHud: true,
  prefetchImageOnDragStart: false,
  showImagePreview: true,
  imagesDir: '',
  imagePerformanceProfile: 'balanced',
  allowPrivateNetwork: false,
  resolveDnsForUrlSafety: true,
  maxDecodedBytes: 160 * 1024 * 1024,
  imageConnectTimeout: 8,
  imageFirstByteTimeoutMs: 10_000,
  imageChunkTimeoutMs: 15_000,
  imageClipboardRetryMaxTotalMs: 1_800,
  imageClipboardRetryMaxDelayMs: 900,
  clipboardEventMinIntervalMs: 80,
  windowPlacement: {
    mode: 'smart_near_cursor',
    customX: 120,
    customY: 120,
  },
};
